const actions = {
    Auth: {
        login: 'AUTH_LOGIN',
        logout: 'AUTH_LOGOUT',
        register: 'AUTH_REGISTER',
        setAccessToken: 'AUTH_SET_ACCESS_TOKEN',
    },
    profile: {
        DATA_FETCHING: 'PROFILE_DATA_FETCHING',
        DATA_FETCHED: 'PROFILE_DATA_FETCHED',
        USER_DATA_EDITED: 'PROFILE_USER_DATA_EDIT',
        IMAGE_UPLOADED: 'PROFILE_IMAGE_UPLOADED',
        DATE_FETCH_ERROR: 'PROFILE_DATA_FETCH_ERROR',
        PROFILE_BLOG_DELETED: 'PROFILE_BLOG_DELETED',
        FETCH_BLOG_AUTHOR: 'FETCH_BLOG_AUTHOR',
    },
    blog: {
        BLOG_FETCHING: 'BLOG_FETCHING',
        BLOG_FETCHED: 'BLOG_FETCHED',
        BLOG_FETCH_ERROR: 'BLOG_FETCH_ERROR',
        BLOG_CREATED: 'BLOG_CREATED',
        BLOG_EDITED: 'BLOG_EDITED',
        BLOG_DELETED: 'BLOG_DELETED',
        BLOG_UPDATED: 'BLOG_UPDATED',
        SINGLE_BLOG_FETCHED: 'SINGLE_BLOG_FETCHED',
        POST_COMMENT: 'POST_COMMENT',
        DELETE_COMMENT: 'DELETE_COMMENT',
        BLOG_LIKED: 'BLOG_LIKED',
        BLOG_FAVORITE: 'BLOG_FAVORITE',
        FETCH_SEARCH_DATA: 'FETCH_SEARCH_DATA',
        FETCH_POPULAR_BLOG: 'FETCH_POPULAR_BLOG',
    },

}


export default actions;